[build-system]
requires = ["hatchling >= 1.27"]
build-backend = "hatchling.build"

[project]
name = "wampy-prolog"
version = "0.2.0"
description = "A Numba-accelerated Warren Abstract Machine implementation for Prolog."
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Dominik Magiera"},
  { name = "Lukas Roehrig"},
  { name = "Frank Jaekel"}
]
keywords = [
  "cognitive science",
  "working memory",
  "simulation",
  "computational cognitive modeling"
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering",
]

dependencies = [
  "numba",
  "numpy",
]

[project.optional-dependencies]
prolog = [
  "janus-swi",
]
dev = [
  "pytest",
]

[project.urls]
Homepage = "https://github.com/cognitive-modeling/WAMpy"
Repository = "https://github.com/cognitive-modeling/WAMpy"
Changelog = "https://github.com/cognitive-modeling/WAMpy/blob/main/CHANGELOG.md"
Issues = "https://github.com/cognitive-modeling/WAMpy/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/wampy"]

[tool.pytest.ini_options]
markers = [
  "requires_numba_jit: marks tests that compile and execute Numba functions",
]
